from datetime import datetime

SPECIAL_CHAR = ['｜', '«', '»', '【', '】', '｜', '•', '…', '=', '・', 'Ｇ', 'Ⅰ', ';', '９']

BAG_MAPPING = {
    "valentino garavani": {
        "rockstud": ["mini", "large", "medium", "small"],
        "roman stud": ["mini", "small", "large", "medium"],
        "rockstud spike": ["mini", "small", "large", "medium"],
        "glam lock": ["mini", "large", "small", "medium"],
        "one stud": ["mini", "large", "small"],
        "vltn": ["large", "medium", "small"],
        "vlogo": ["mini", "large", "medium", "small"],
        "vsling": ["large", "small"],
        "atelier": ["small", "large", "medium"]
    },
    "loewe": {
        "cushion": ["large", "small"],
        "anagram": ["mini", "medium", "small"],
        "amazona": ["large"],
        "puzzle": ["mini", "large", "medium", "small"],
        "gate": ["mini", "large", "medium", "small"],
        "flamenco": ["mini", "large", "small", "medium"],
        "hammock": ["mini", "large", "medium", "small"],
        "goya": ["mini", "medium", "small"],
        "basket": ["small"],
        "raffia": ["mini", "large", "medium", "small"]
    },
    "cartier": {
        "marcello": ["large"],
        "cabochon": ["mini"],
        "must de": []
    },
    "dior": {
        "lady dior": ["mini", "large", "small", "medium"],
        "saddle": ["mini", "small"],
        "book tote": ["mini", "small", "large", "medium"],
        "oblique": ["mini", "large", "medium", "small"],
        "miss dior": ["mini"],
        "bobby": ["large", "medium", "small"],
        "diorama": ["large", "medium", "small"],
        "30 montaigne": ["small"],
        "cannage": ["mini", "large", "medium", "small"],
        "diorissimo": ["mini", "large", "medium"],
        "wallet on chain": []
    },
    "celine": {
        "16": ["mini", "medium", "small"],
        "triomphe": ["mini", "clutch", "medium", "flap", "cabas", "small"],
        "classic box": ["mini", "flap", "medium"],
        "trapeze": ["medium", "small"],
        "luggage": ["mini", "medium", "nano", "micro"],
        "trio": ["clutch", "small"],
        "belt": ["mini", "medium", "nano", "micro", "small"],
        "big": ["nano", "small"],
        "vertical": ["mini", "cabas", "small"],
        "phantom": ["phantom", "small"],
        "vintage": ["mini", "flap"],
        "cabas": ["clutch", "cabas", "small"],
        "trotteur": ["small"],
        "ava": ["mini", "medium"],
        "clasp": ["mini", "medium"]
    },
    "balenciaga": {
        "classic": ["mini", "large", "small", "medium"],
        "papier": ["mini"],
        "ville top handle": ["mini", "small"],
        "city": ["medium"],
        "neo classic": ["mini", "small", "medium"],
        "giant": ["mini", "medium"],
        "day": ["small"],
        "navy": ["medium", "small"],
        "le cagole": ["mini", "medium", "small"],
        "hourglass": ["mini", "medium", "small"],
        "hardware": ["mini", "small", "medium"],
        "everyday": ["small"]
    },
    "chanel": {
        "19": ["jumbo", "19"],
        "22": ["jumbo", "pouch", "mini", "22", "clutch", "225", "19", "maxi", "small"],
        "31": ["mini", "large", "19", "flap"],
        "chanel shopping": ["large", "19", "small"],
        "deauville": ["pouch", "mini", "clutch", "medium", "large", "small"],
        "timeless": ["jumbo", "pouch", "mini", "clutch", "small", "22", "large", "19", "flap", "camera", "medium"],
        "mademoiselle": ["22", "clutch", "medium", "large", "flap", "small"],
        "boy": ["jumbo", "new medium", "mini", "clutch", "medium", "large", "flap", "old medium", "small"],
        "2.55": ["mini", "small", "clutch", "large", "maxi", "medium"],
        "gabrielle": ["new medium", "small", "clutch", "large", "maxi", "medium"],
        "vintage": ["jumbo", "pouch", "mini", "clutch", "medium", "camera case", "flap", "maxi", "camera", "small"],
        "shopping": ["mini", "small", "22", "large", "19", "maxi", "medium"],
        "top handle": ["jumbo", "pouch", "mini", "clutch", "top handle", "large", "19", "flap", "small"],
        "wallet on chain": ["pouch", "mini", "clutch", "22", "19", "225", "flap", "maxi"],
        "bowling": ["jumbo", "mini", "small", "large", "maxi", "medium"],
        "vanity": ["mini", "clutch", "small", "large", "225", "medium"],
        "cambon": ["pouch", "22", "clutch", "large", "19", "flap", "maxi", "medium"],
        "camera": ["camera", "19", "camera case", "small"],
        "coco cocoon": ["large", "medium", "small"],
        "hobo": ["pouch", "small", "mini", "22", "large", "19", "maxi", "medium"],
        "trendy cc": ["mini", "clutch", "small", "flap", "medium"],
        "executive": ["mini", "large", "medium", "small"],
        "messenger": ["jumbo", "mini", "small", "22", "large", "19", "225", "flap", "camera", "medium"],
        "coco": ["jumbo", "mini", "clutch", "medium", "22", "mini square", "large", "19", "flap", "small"],
        "coco handle": ["mini", "large", "flap", "small"],
        "reissue": ["jumbo", "pouch", "mini", "22", "clutch", "225", "19", "camera case", "flap", "camera", "small"],
        "classic flap": ["jumbo", "pouch", "mini", "clutch", "22", "225", "19", "flap", "maxi", "camera", "small"]
    },
    "fendi": {
        "baguette": ["mini", "large", "medium", "small"],
        "by the way": ["mini", "large", "small", "medium"],
        "peekaboo": ["mini", "medium", "large", "petite", "small"],
        "selleria": ["mini", "small", "large", "medium"],
        "runaway": ["large", "medium", "small"],
        "fendigraphy": ["mini", "medium", "small"],
        "sunshine": ["mini", "large", "small", "medium"],
        "kan i": ["mini", "medium", "small"],
        "zucca": ["mini", "large", "medium", "small"],
        "first": ["small", "medium"],
        "zucchino": ["mini", "medium", "small"],
        "mon tresor": ["mini", "small"],
        "croissant": ["mini"]
    },
    "gucci": {
        "1955": ["mini", "large", "medium", "small"],
        "jackie": ["mini", "large", "medium", "small"],
        "gg marmont": ["mini", "large", "medium", "small"],
        "bamboo": ["mini", "small", "large", "medium"],
        "shopping": ["mini", "large", "small", "medium"],
        "sukey": ["medium"],
        "blondie": ["mini", "small", "medium"],
        "ophidia": ["mini", "large", "medium", "small"],
        "guccissima": ["mini", "large", "medium", "small"],
        "vintage": ["mini", "large", "medium", "small"],
        "sylvie": ["mini", "small", "medium"],
        "dionysus": ["mini", "large", "medium", "small"],
        "supreme gg": ["mini", "large"],
        "interlocking g": ["mini", "small", "large", "medium"],
        "messenger": ["mini", "large", "medium", "small"],
        "boston": ["mini", "small", "large", "medium"],
        "eclipse": ["large", "small"],
        "soho": ["mini", "large", "medium", "small"],
        "padlock": ["mini", "medium", "small"],
        "abbey": ["medium"],
        "tote": ["mini", "large", "medium", "small"],
        "neo vintage": ["mini", "medium", "small"],
        "diana": ["mini", "large", "medium", "small"],
        "pelham": ["medium", "small"]
    },
    "hermes": {
        'so kelly': ['22', '26', '28'],
        "kelly": ["33", "24", "mini", "22", "34", "40", "28", "elan", "32", "35", "25", "26"],
        "constance": ["25", "mini", "elan", "29", "18", "24"],
        "berline": ["mini", "28", "mm", "32", "31"],
        "birkin": ["30", "50", "40", "32", "35", "25"],
        "bolide": ["27", "mini", "30", "gm", "28", "35", "45", "25", "31"],
        "picotin": ["pm", "22", "gm", "mm", "18", "micro"],
        "roulis": ["mini", "18", "23"],
        "evelyne": ["pm", "mini", "gm", "28", "25"],
        "herbag": ["cabin", "27", "30", "39", "gm", "50", "28", "mm", "36", "31"],
        "lindy": ["mini", "30", "26", "34"],
        "trim": ["24", "31"],
        "victoria": ["elan", "35"],
        "garden party": ["pm", "33", "30", "gm", "36", "mm", "24"],
        "jypsiere": ["mini", "31", "28"],
        "jige": ["elan"],
        "herline": ["mm", "gm", "pm"]
    },
    "louis vuitton": {
        "editions limitees": [],
        "malle": ["mm", "bb", "pm", "petit"],
        "turenne": ["mm", "gm", "nano", "pm"],
        "musette": ["mini", "20", "gm", "pm"],
        "bagatelle": ["25", "nm"],
        "keepall": ["bb", "pm", "30", "gm", "50", "mm", "20", "45", "35", "55", "25"],
        "lockme": ["mini", "mm", "bb", "pm"],
        "saintonge": [],
        "capucines": ["bb", "pm", "mini", "gm", "mm", "25"],
        "onthego": ["mm", "30", "gm", "pm"],
        "ellipse": ["bb", "pm", "gm", "nm", "mm"],
        "coussin": ["mm", "gm", "bb", "pm"],
        "neverfull": ["bb", "pm", "30", "gm", "50", "nm", "mm", "20", "pochette", "petit"],
        "croisette": ["purse", "pm", "30", "gm", "nm"],
        "artsy": ["mm", "gm", "25"],
        "alma": ["bb", "pm", "mini", "30", "gm", "nano", "mm", "20", "45", "55"],
        "saumur": ["mini", "30", "bb", "35"],
        "montsouris": ["pm", "mini", "gm", "nm", "mm"],
        "pochette": ["30", "nm", "mm", "20", "pochette"],
        "speedy": ["pm", "mini", "30", "gm", "nano", "nm", "mm", "20", "35", "55", "25"],
        "dauphine": ["bb", "pm", "mini", "mm", "pochette"],
        "batignolles": [],
        "hampstead": ["mm", "pm"],
        "idylle": ["pm", "mini", "30", "mm", "20", "45"],
        "sling": ["45", "nm"],
        "papillon": ["bb", "pm", "mini", "30", "nano", "nm", "pochette"],
        "brazza": ["25", "20", "35"],
        "messenger": ["bb", "pm", "mini", "30", "gm", "nano", "nm", "mm", "20", "pochette", "35", "petit", "55", "25"],
        "macassar": ["pm", "nm", "mm", "45", "55", "25"],
        "metis": [],
        "pont neuf": ["mm", "gm", "nm", "pm"],
        "eva": [],
        "palm springs backpack": ["mini", "mm", "pm"],
        "looping": ["mini", "30", "gm", "mm", "20"],
        "soufflot": ["bb", "mini", "mm", "20", "55"],
        "trevi": ["20", "gm", "pm"],
        "galliera": ["mm", "20", "gm", "pm"],
        "vanity": ["bb", "pm", "mini", "nano", "20", "55"],
        "saint jacques": ["30", "gm", "nm", "pm"],
        "piano": ["30", "pm"],
        "twist": ["purse", "bb", "pm", "mini", "gm", "mm", "25"],
        "brea": ["mm", "gm", "pm"],
        "zippy": ["purse", "mini", "30", "gm", "20", "35", "55", "25"],
        "sarah": ["mini", "30", "50", "nm", "20", "45", "25"],
        "geant": ["55", "25", "30", "50"],
        "boite chapeau": ["pm", "mini", "mm", "petit", "25"],
        "trunk": ["bb", "pm", "50", "nm", "mm", "45", "petit"],
        "lockit": ["bb", "pm", "gm", "mm", "20"],
        "montaigne": ["bb", "pm", "gm", "nano", "mm", "pochette"],
        "multi": ["purse", "bb", "pm", "mini", "30", "gm", "mm", "20", "35", "petit", "55", "25"],
        "totally": ["mm", "20", "gm", "pm"],
        "lussac": ["20", "35"],
        "cannes": [],
        "reporter": ["mm", "gm", "pm"],
        "sac plat": ["bb", "pm", "mini", "nm", "45", "petit", "25"],
        "florentine": ["pm", "30", "pochette", "55", "25"],
        "siena": ["mm", "20", "gm", "pm"],
        "bucket": ["pm", "30", "gm", "nano", "mm", "20", "35", "petit", "55", "25"],
        "soft trunk": ["mini", "30", "mm"],
        "wilshire": ["mm", "pm"],
        "porte documents": ["mm", "pochette", "50", "pm"],
        "deauville": ["55", "mini", "20"],
        "tivoli": ["gm", "pm"],
        "mabillon": ["mini"],
        "saleya": ["mm", "gm", "pm"],
        "boulogne": ["pm", "mini", "30", "gm", "50", "nm", "20", "35"],
        "felicie": [],
        "danube": ["pm", "mini", "30", "gm", "20"],
        "pegase": ["mini", "30", "50", "45", "55"],
        "marin": ["mm", "gm", "bb", "pm"],
        "city steamer": ["mini", "mm", "gm", "pm"],
        "noe": ["purse", "bb", "mini", "30", "gm", "nano", "nm", "mm", "20", "petit"],
        "odeon": ["pm", "30", "nm", "mm", "20"],
        "cartouchiere": ["pm", "mini", "gm", "mm", "20", "petit", "25"],
        "bloomsbury": ["gm", "pm"],
        "randonnee": ["pm", "30", "gm", "20", "pochette", "45"],
        "trocadero": ["55", "25", "30", "20"]
    },
    "prada": {
        "city calf": ["mini", "small", "large", "medium"],
        "promenade": ["medium", "small"],
        "nylon": ["mini", "small", "medium"],
        "cleo": ["mini", "small", "medium"],
        "galleria": ["small", "large", "medium"],
        "canapa": ["mini", "large", "medium", "small"],
        "diagramme": ["mini", "small", "medium"],
        "double": ["mini", "small", "large", "medium"],
        "cahier": ["small"],
        "vitello": ["mini", "large", "medium", "small"]
    },
    "saint laurent": {
        "sac de jour": ["medium", "nano", "baby", "large", "small"],
        "niki": ["mini", "large", "baby", "medium"],
        "sunset": ["mini", "small", "medium"],
        "duffle": ["mini", "baby", "6", "12", "24"],
        "enveloppe": ["medium"],
        "loulou": ["toy", "large", "medium", "small"],
        "chyc": [],
        "kate": ["mini", "medium", "toy", "12", "small"],
        "puffer": ["mini", "medium", "small"],
        "shopping": ["maxi", "mini"],
        "rive gauche": ["6", "large", "medium", "small"],
        "lou": ["mini", "baby", "small"],
        "wallet on chain": ["6", "12"],
        "envelope": ["large", "small"]
    },
    "bottega veneta": {
        "veneta": ["mini", "large", "medium", "small"],
        "cassette": ["mini", "large", "small"],
        "the shoulder pouch": ["medium", "small"],
        "nodini": ["small"],
        "the pouch": ["mini"],
        "olimpia": ["small", "medium"],
        "jodie": ["mini", "small"],
        "pouch": ["mini", "large", "medium", "small"]
    },
    "bvlgari": {
        "isabella rossellini": [],
        "serpenti": ["mini", "large", "medium", "small"]
    },
    "chloe": {
        "drew": ["mini", "medium", "small"],
        "aby": ["mini", "large", "small", "medium"],
        "faye": ["mini", "medium", "small"],
        "pixie": ["mini", "medium", "small"],
        "marcie": ["mini", "small", "large", "medium"],
        "nile": ["mini", "medium", "small"],
        "paraty": ["small", "medium"],
        "hudson": ["mini", "small", "medium"],
        "paddington": [],
        "elsie": []
    },
    "givenchy": {
        "antigona": ["mini", "large", "medium", "small"],
        "nightingale": ["mini", "medium", "small"],
        "pandora": ["mini", "large", "small", "medium"],
        "infinity": ["medium"],
        "gv3": ["mini", "small"],
        "shark": ["medium"],
        "lucrezia": ["mini", "medium"]
    },
    "miu miu": {
        "miu wander": ["mini"],
        "coffer": [],
        "vitello": [],
        "matelasse": ["mini", "large"]
    },
    "goyard": {
        "saigon": ["mini"],
        "anjou": ["mini"],
        "cap vert": ["mini"]
    }
}

BAG_DETAILS = {
    "material": [
        "monogram canvas",
        "canvas",
        "denim",
        "fabric",
        "nylon",
        "wicker",
        "silk",
        "cloth",
        "velvet",
        "fur",
        "suede",
        "wool",
        "patent leather",
        "lambskin",
        "calfskin",
        "buffalo",
        "goatskin",
        "sharkskin",
        "lizard",
        "crocodile",
        "ostrich",
        "python",
        "leather",
    ],
    "color": [
        "beige",
        "black",
        "blue",
        "brown",
        "gold",
        "green",
        "gray",
        "grey",
        "khaki",
        "monogram",
        "orange",
        "pink",
        "plum",
        "purple",
        "burgundy",
        "red",
        "rouge",
        "white",
        "yellow",
        "indigo",
        "silver",
        "metallic",
        "transparent",
        "taupe",
        "coral",
        "teal",
        "lilac",
        "turquoise",
        "tan",
        "ivory",
        "blush",
        "peach",
        "bronze",
        "anthracite",
        "damier",
        "etoupe",
        "camel",
        "rainbow",
        "multicolor",
        "navy",
        "gilt"
    ],
    "category": [
        "backpack",
        "bucket",
        "clutch",
        "coin purse",
        "satchel",
        "suitcase",
        "top handle",
        "tote",
        "trunk",
        "travel bag",
        "wallet",
        "briefcase",
        "vanity case",
        "crossbody",
        "duffle",
        "handbag",
        "hobo",
        "messenger",
        "pouch",
        "shoulder bag",
        "bag"
    ],
    "collection":
        {
            "loewe": [
                "flamenco",
                "hammock",
                "amazona",
                "anagram",
                "cushion",
                "raffia",
                "basket",
                "puzzle",
                "goya",
                "gate"
            ],
            "bvlgari": [
                "isabella rossellini",
                "serpenti"
            ],
            "valentino garavani": [
                "rockstud spike",
                "roman stud",
                "glam lock",
                "one stud",
                "rockstud",
                "atelier",
                "vsling",
                "vlogo",
                "vltn"
            ],
            "saint laurent": [
                "wallet on chain",
                "rive gauche",
                "sac de jour",
                "enveloppe",
                "envelope",
                "shopping",
                "puffer",
                "loulou",
                "duffle",
                "sunset",
                "kate",
                "chyc",
                "niki",
                "lou"
            ],
            "louis vuitton": [
                "palm springs backpack",
                "editions limitees",
                "porte documents",
                "boite chapeau",
                "saint jacques",
                "cartouchiere",
                "city steamer",
                "batignolles",
                "bloomsbury",
                "soft trunk",
                "florentine",
                "montsouris",
                "trocadero",
                "randonnee",
                "deauville",
                "montaigne",
                "pont neuf",
                "messenger",
                "hampstead",
                "croisette",
                "neverfull",
                "capucines",
                "saintonge",
                "bagatelle",
                "boulogne",
                "mabillon",
                "wilshire",
                "sac plat",
                "reporter",
                "galliera",
                "soufflot",
                "macassar",
                "papillon",
                "dauphine",
                "pochette",
                "felicie",
                "totally",
                "looping",
                "coussin",
                "ellipse",
                "onthego",
                "keepall",
                "musette",
                "turenne",
                "idylle",
                "pegase",
                "danube",
                "saleya",
                "tivoli",
                "bucket",
                "cannes",
                "lussac",
                "lockit",
                "vanity",
                "brazza",
                "speedy",
                "saumur",
                "lockme",
                "odeon",
                "marin",
                "siena",
                "multi",
                "trunk",
                "geant",
                "sarah",
                "zippy",
                "twist",
                "piano",
                "trevi",
                "metis",
                "sling",
                "artsy",
                "malle",
                "brea",
                "alma",
                "noe",
                "eva"
            ],
            "cartier": [
                "cabochon",
                "marcello",
                "must de"
            ],
            "fendi": [
                "fendigraphy",
                "mon tresor",
                "by the way",
                "croissant",
                "zucchino",
                "sunshine",
                "selleria",
                "peekaboo",
                "baguette",
                "runaway",
                "first",
                "zucca",
                "kan i"
            ],
            "gucci": [
                "interlocking g",
                "neo vintage",
                "supreme gg",
                "guccissima",
                "gg marmont",
                "messenger",
                "dionysus",
                "shopping",
                "padlock",
                "eclipse",
                "vintage",
                "ophidia",
                "blondie",
                "pelham",
                "boston",
                "sylvie",
                "bamboo",
                "jackie",
                "diana",
                "abbey",
                "sukey",
                "tote",
                "soho",
                "1955"
            ],
            "miu miu": [
                "miu wander",
                "matelasse",
                "vitello",
                "coffer"
            ],
            "goyard": [
                "cap vert",
                "saigon",
                "anjou"
            ],
            "prada": [
                "diagramme",
                "promenade",
                "city calf",
                "galleria",
                "vitello",
                "cahier",
                "double",
                "canapa",
                "nylon",
                "cleo"
            ],
            "hermes": [
                "garden party",
                "constance",
                "jypsiere",
                "victoria",
                "so kelly",
                "herline",
                "evelyne",
                "picotin",
                "berline",
                "herbag",
                "roulis",
                "bolide",
                "birkin",
                "lindy",
                "kelly",
                "jige",
                "trim"
            ],
            "chanel": [
                "wallet on chain",
                "chanel shopping",
                "classic flap",
                "mademoiselle",
                "coco handle",
                "coco cocoon",
                "top handle",
                "messenger",
                "executive",
                "trendy cc",
                "gabrielle",
                "deauville",
                "shopping",
                "timeless",
                "reissue",
                "bowling",
                "vintage",
                "camera",
                "cambon",
                "vanity",
                "coco",
                "hobo",
                "2.55",
                "boy",
                "22",
                "31",
                "19"
            ],
            "givenchy": [
                "nightingale",
                "lucrezia",
                "infinity",
                "antigona",
                "pandora",
                "shark",
                "gv3"
            ],
            "balenciaga": [
                "ville top handle",
                "neo classic",
                "hourglass",
                "le cagole",
                "everyday",
                "hardware",
                "classic",
                "papier",
                "giant",
                "navy",
                "city",
                "day"
            ],
            "dior": [
                "wallet on chain",
                "30 montaigne",
                "diorissimo",
                "miss dior",
                "book tote",
                "lady dior",
                "cannage",
                "diorama",
                "oblique",
                "saddle",
                "bobby"
            ],
            "bottega veneta": [
                "the shoulder pouch",
                "the pouch",
                "cassette",
                "olimpia",
                "nodini",
                "veneta",
                "pouch",
                "jodie"
            ],
            "chloe": [
                "paddington",
                "hudson",
                "paraty",
                "marcie",
                "elsie",
                "pixie",
                "nile",
                "faye",
                "drew",
                "aby"
            ],
            "celine": [
                "classic box",
                "trotteur",
                "vertical",
                "triomphe",
                "vintage",
                "phantom",
                "luggage",
                "trapeze",
                "clasp",
                "cabas",
                "belt",
                "trio",
                "ava",
                "big",
                "16"
            ]
        }
}


def month_year_string():
    current_year = datetime.now().year
    year_string = [str(current_year - i) for i in range(50)]

    year_month_string = []
    for i in range(1, 13):
        for year in year_string:
            year_month_string.append(str(i).rjust(2, '0') + year)

    return year_month_string
